-- ============================================================================
-- Sanix AluExpert ERP — Catalogue étendu d'ouvrages (menuiserie aluminium & inox)
-- ============================================================================
-- Composants utilisés par les ~77 nouveaux ouvrages du Configurateur (fenêtres, coulissants, portes,
-- façades, fermetures, pergolas, garde-corps, portails, douche, composite). PRIX INDICATIFS en FCFA,
-- à ajuster dans Composants & consommables. Les composants déjà présents ne sont pas modifiés.
-- ============================================================================
insert into public.composants (code, standing, nom, type, famille, unite, prix_unitaire) values
  ('P-MEN-001', 'standard', 'Meneau / traverse aluminium', 'Composant', 'Profilé aluminium', 'ml', 9800),
  ('P-COU-RH', 'standard', 'Rail haut coulissant', 'Composant', 'Profilé aluminium', 'ml', 9500),
  ('P-COU-RB', 'standard', 'Rail bas coulissant', 'Composant', 'Profilé aluminium', 'ml', 10500),
  ('P-COU-MD', 'standard', 'Montant dormant coulissant', 'Composant', 'Profilé aluminium', 'ml', 8500),
  ('P-COU-OV', 'standard', 'Ouvrant coulissant (montant/traverse)', 'Composant', 'Profilé aluminium', 'ml', 9800),
  ('P-LEV-OV', 'standard', 'Ouvrant levant-coulissant renforcé', 'Composant', 'Profilé aluminium', 'ml', 16500),
  ('P-POR-DOR', 'standard', 'Dormant de porte', 'Composant', 'Profilé aluminium', 'ml', 11500),
  ('P-POR-OUV', 'standard', 'Ouvrant de porte (montant large)', 'Composant', 'Profilé aluminium', 'ml', 13500),
  ('P-MR-MON', 'standard', 'Montant de mur-rideau 50 mm', 'Composant', 'Profilé aluminium', 'ml', 18500),
  ('P-MR-TRA', 'standard', 'Traverse de mur-rideau 50 mm', 'Composant', 'Profilé aluminium', 'ml', 15500),
  ('P-MR-CAP', 'standard', 'Serreur + capot de mur-rideau', 'Composant', 'Profilé aluminium', 'ml', 6500),
  ('P-VER-40', 'standard', 'Profilé verrière 40×20 aspect acier', 'Composant', 'Profilé aluminium', 'ml', 7200),
  ('P-CLO-001', 'standard', 'Profilé de cloison (rail / montant)', 'Composant', 'Profilé aluminium', 'ml', 6800),
  ('P-GUI-OV', 'standard', 'Ouvrant guillotine', 'Composant', 'Profilé aluminium', 'ml', 9800),
  ('P-PLI-OV', 'standard', 'Ouvrant pliant (accordéon)', 'Composant', 'Profilé aluminium', 'ml', 12500),
  ('P-PLI-RAIL', 'standard', 'Rail haut/bas porte pliante', 'Composant', 'Profilé aluminium', 'ml', 14500),
  ('PAN-SAND-24', 'standard', 'Panneau sandwich alu 24 mm (remplissage)', 'Composant', 'Panneau', 'm2', 18500),
  ('TOL-ALU-20', 'standard', 'Tôle aluminium 2 mm laquée', 'Composant', 'Panneau', 'm2', 16500),
  ('TOL-PERF-INX', 'standard', 'Tôle inox perforée 1,5 mm', 'Composant', 'Panneau', 'm2', 42000),
  ('VIT-FEU-442', 'standard', 'Verre feuilleté 44.2 (sécurité)', 'Composant', 'Vitrage', 'm2', 19500),
  ('VIT-TRE-8', 'standard', 'Verre trempé 8 mm (douche)', 'Composant', 'Vitrage', 'm2', 24000),
  ('VIT-TRE-10', 'standard', 'Verre trempé 10 mm (porte tout verre)', 'Composant', 'Vitrage', 'm2', 29000),
  ('VIT-POLY-16', 'standard', 'Polycarbonate alvéolaire 16 mm', 'Composant', 'Vitrage', 'm2', 9500),
  ('VIT-HUB-001', 'standard', 'Hublot vitré de porte sectionnelle', 'Composant', 'Vitrage', 'unite', 18000),
  ('JNT-FRP-001', 'standard', 'Joint de frappe EPDM', 'Consommable', 'Joint & étanchéité', 'ml', 650),
  ('JNT-MR-001', 'standard', 'Joint EPDM de mur-rideau', 'Consommable', 'Joint & étanchéité', 'ml', 1200),
  ('CON-SIL-STR', 'standard', 'Silicone structurel (VEC)', 'Consommable', 'Consommable atelier', 'cartouche', 9500),
  ('FIX-CHV-001', 'standard', 'Cheville + vis de fixation dormant', 'Consommable', 'Visserie & fixations', 'unite', 250),
  ('FIX-MR-ATT', 'standard', 'Attache de mur-rideau (équerre de dalle)', 'Composant', 'Visserie & fixations', 'unite', 6500),
  ('FIX-SCE-001', 'standard', 'Patte de scellement', 'Composant', 'Visserie & fixations', 'unite', 900),
  ('QUI-CRM-001', 'standard', 'Crémone + poignée de fenêtre', 'Composant', 'Quincaillerie', 'unite', 6500),
  ('QUI-VER-001', 'standard', 'Verrou de semi-fixe', 'Composant', 'Quincaillerie', 'unite', 2200),
  ('QUI-OB-KIT', 'standard', 'Kit ferrage oscillo-battant', 'Composant', 'Quincaillerie', 'unite', 38000),
  ('QUI-CMP-SOU', 'standard', 'Compas de soufflet', 'Composant', 'Quincaillerie', 'unite', 4500),
  ('QUI-BRA-PRJ', 'standard', 'Paire de bras de projection (italienne)', 'Composant', 'Quincaillerie', 'unite', 14500),
  ('QUI-PIV-001', 'standard', 'Paire de pivots avec frein', 'Composant', 'Quincaillerie', 'unite', 17500),
  ('QUI-GUI-RES', 'standard', 'Balancier / ressorts de guillotine', 'Composant', 'Quincaillerie', 'unite', 16000),
  ('QUI-ROU-001', 'standard', 'Roulette réglable de coulissant', 'Composant', 'Quincaillerie', 'unite', 1800),
  ('QUI-FER-COU', 'standard', 'Fermeture à crochet + poignée coquille', 'Composant', 'Quincaillerie', 'unite', 5500),
  ('QUI-BUT-001', 'standard', 'Butée de coulissant', 'Composant', 'Quincaillerie', 'unite', 600),
  ('QUI-LEV-KIT', 'standard', 'Kit levant-coulissant (chariots + levier)', 'Composant', 'Quincaillerie', 'unite', 95000),
  ('QUI-CHA-PLI', 'standard', 'Charnière de porte pliante', 'Composant', 'Quincaillerie', 'unite', 6500),
  ('QUI-CHR-PLI', 'standard', 'Chariot de porte pliante', 'Composant', 'Quincaillerie', 'unite', 12500),
  ('QUI-CYL-001', 'standard', 'Cylindre de sécurité 5 clés', 'Composant', 'Quincaillerie', 'unite', 9500),
  ('QUI-SER-3P', 'standard', 'Serrure 3 points de porte', 'Composant', 'Quincaillerie', 'unite', 42000),
  ('QUI-PIV-SOL', 'standard', 'Pivot de sol avec frein (va-et-vient)', 'Composant', 'Quincaillerie', 'unite', 85000),
  ('QUI-PIV-POR', 'standard', 'Pivot de porte désaxée', 'Composant', 'Quincaillerie', 'unite', 120000),
  ('QUI-POI-TIR', 'standard', 'Poignée tirant inox', 'Composant', 'Quincaillerie', 'unite', 18000),
  ('LAM-VR-39', 'standard', 'Lame de volet roulant alu 39 mm isolée', 'Composant', 'Profilé aluminium', 'ml', 2600),
  ('LAM-VR-55', 'standard', 'Lame de volet alu 55 mm', 'Composant', 'Profilé aluminium', 'ml', 3400),
  ('LAM-GA-77', 'standard', 'Lame de porte de garage alu 77 mm', 'Composant', 'Profilé aluminium', 'ml', 5200),
  ('LAM-RM-100', 'standard', 'Lame de rideau métallique 100 mm', 'Composant', 'Profilé aluminium', 'ml', 6800),
  ('LAM-RM-MAI', 'standard', 'Tablier grille maillée (anneaux)', 'Composant', 'Panneau', 'm2', 38000),
  ('TOI-MOU-ENR', 'standard', 'Toile de moustiquaire enroulable', 'Consommable', 'Vitrage', 'm2', 4500),
  ('LAM-FIN', 'standard', 'Lame finale avec joint', 'Composant', 'Profilé aluminium', 'ml', 4500),
  ('P-ENR-COF', 'standard', 'Coffre de volet / rideau', 'Composant', 'Profilé aluminium', 'ml', 12500),
  ('P-ENR-COU', 'standard', 'Coulisse avec joint brosse', 'Composant', 'Profilé aluminium', 'ml', 5500),
  ('AXE-OCT-60', 'standard', 'Axe octogonal Ø60', 'Composant', 'Profilé aluminium', 'ml', 5800),
  ('AXE-RM-102', 'standard', 'Axe de rideau métallique Ø102 + ressorts', 'Composant', 'Quincaillerie', 'ml', 22000),
  ('QUI-ATT-TAB', 'standard', 'Attache tablier / verrou', 'Composant', 'Quincaillerie', 'unite', 650),
  ('QUI-JOU-001', 'standard', 'Paire de joues / flasques de coffre', 'Composant', 'Quincaillerie', 'unite', 6500),
  ('MOT-TUB-001', 'standard', 'Moteur tubulaire filaire + inverseur', 'Composant', 'Motorisation', 'unite', 75000),
  ('MOT-RID-001', 'standard', 'Moteur central de rideau métallique', 'Composant', 'Motorisation', 'unite', 260000),
  ('QUI-MAN-001', 'standard', 'Treuil + manivelle', 'Composant', 'Quincaillerie', 'unite', 18000),
  ('QUI-SER-RID', 'standard', 'Serrure de sol de rideau', 'Composant', 'Quincaillerie', 'unite', 22000),
  ('PAN-SEC-40', 'standard', 'Panneau sectionnel isolé 40 mm', 'Composant', 'Panneau', 'm2', 32000),
  ('P-SEC-RAIL', 'standard', 'Rail de porte sectionnelle', 'Composant', 'Profilé aluminium', 'ml', 7500),
  ('QUI-RES-TOR', 'standard', 'Ressort de torsion + tambour', 'Composant', 'Quincaillerie', 'unite', 48000),
  ('QUI-GAL-001', 'standard', 'Galet + support de panneau', 'Composant', 'Quincaillerie', 'unite', 3500),
  ('QUI-CHA-SEC', 'standard', 'Charnière intermédiaire de panneau', 'Composant', 'Quincaillerie', 'unite', 2500),
  ('MOT-PLA-001', 'standard', 'Motorisation plafond de porte de garage', 'Composant', 'Motorisation', 'unite', 220000),
  ('P-CAD-LAM', 'standard', 'Cadre porte-lames (persienne / volet)', 'Composant', 'Profilé aluminium', 'ml', 7800),
  ('LAM-PER-50', 'standard', 'Lame de persienne 50 mm', 'Composant', 'Profilé aluminium', 'ml', 2400),
  ('LAM-BS-150', 'standard', 'Lame brise-soleil aile d’avion 150 mm', 'Composant', 'Profilé aluminium', 'ml', 9500),
  ('LAM-BSO-80', 'standard', 'Lame orientable BSO 80 mm', 'Composant', 'Profilé aluminium', 'ml', 3800),
  ('LAM-CLA-100', 'standard', 'Lame claustra 100×30', 'Composant', 'Profilé aluminium', 'ml', 5200),
  ('QUI-EMB-LAM', 'standard', 'Embout / clip de lame', 'Composant', 'Quincaillerie', 'unite', 450),
  ('FIX-CONS-BS', 'standard', 'Console de brise-soleil', 'Composant', 'Visserie & fixations', 'unite', 9500),
  ('QUI-PEN-001', 'standard', 'Penture + gond de volet battant', 'Composant', 'Quincaillerie', 'unite', 6500),
  ('QUI-ESP-001', 'standard', 'Espagnolette de volet', 'Composant', 'Quincaillerie', 'unite', 8500),
  ('MOT-BSO-001', 'standard', 'Moteur de BSO', 'Composant', 'Motorisation', 'unite', 95000),
  ('P-PER-POT', 'standard', 'Poteau de pergola 150×150', 'Composant', 'Profilé aluminium', 'ml', 32000),
  ('P-PER-POU', 'standard', 'Poutre-chéneau de pergola', 'Composant', 'Profilé aluminium', 'ml', 36000),
  ('LAM-PER-200', 'standard', 'Lame orientable de pergola 200 mm', 'Composant', 'Profilé aluminium', 'ml', 14500),
  ('LAM-PER-FIX', 'standard', 'Chevron / lame fixe de toiture', 'Composant', 'Profilé aluminium', 'ml', 9800),
  ('MOT-PER-001', 'standard', 'Vérin / moteur de lames de pergola', 'Composant', 'Motorisation', 'unite', 185000),
  ('PLA-PER-001', 'standard', 'Platine d’ancrage de poteau', 'Composant', 'Visserie & fixations', 'unite', 14500),
  ('FIX-MUR-PER', 'standard', 'Fixation murale de pergola adossée', 'Composant', 'Visserie & fixations', 'unite', 4500),
  ('P-AUV-MUR', 'standard', 'Profil mural d’auvent', 'Composant', 'Profilé aluminium', 'ml', 16500),
  ('TIR-INX-001', 'standard', 'Tirant inox + rotules', 'Composant', 'Quincaillerie', 'unite', 38000),
  ('TUB-ALU-80', 'standard', 'Tube aluminium 80×40 (cadre)', 'Composant', 'Profilé aluminium', 'ml', 8800),
  ('TUB-ALU-25', 'standard', 'Tube aluminium 25×25 (barreau)', 'Composant', 'Profilé aluminium', 'ml', 3200),
  ('LAM-POR-150', 'standard', 'Lame de portail / clôture 150 mm', 'Composant', 'Profilé aluminium', 'ml', 6500),
  ('TUB-INX-40', 'standard', 'Tube inox 40×40 (cadre)', 'Composant', 'Profilé aluminium', 'ml', 19500),
  ('TUB-INX-20', 'standard', 'Tube inox Ø20 (barreau)', 'Composant', 'Profilé aluminium', 'ml', 7800),
  ('QUI-GON-001', 'standard', 'Gond réglable de portail', 'Composant', 'Quincaillerie', 'unite', 9500),
  ('QUI-SER-POR', 'standard', 'Serrure de portail + gâche', 'Composant', 'Quincaillerie', 'unite', 28000),
  ('QUI-ROU-POR', 'standard', 'Roue à gorge de portail coulissant', 'Composant', 'Quincaillerie', 'unite', 14000),
  ('QUI-GUI-POR', 'standard', 'Guide haut à galets', 'Composant', 'Quincaillerie', 'unite', 16000),
  ('P-RAI-SOL', 'standard', 'Rail au sol à sceller', 'Composant', 'Profilé aluminium', 'ml', 6500),
  ('MOT-POR-BAT', 'standard', 'Motorisation portail battant (2 vérins)', 'Composant', 'Motorisation', 'unite', 320000),
  ('MOT-POR-COU', 'standard', 'Motorisation portail coulissant', 'Composant', 'Motorisation', 'unite', 260000),
  ('POT-CLO-001', 'standard', 'Poteau de clôture aluminium', 'Composant', 'Profilé aluminium', 'ml', 12500),
  ('BAR-DEF-012', 'standard', 'Barreau de défense acier galva Ø12', 'Composant', 'Profilé aluminium', 'ml', 2200),
  ('POT-ALU-001', 'standard', 'Poteau de garde-corps alu 50×50', 'Composant', 'Profilé aluminium', 'ml', 14500),
  ('MC-ALU-001', 'standard', 'Main courante aluminium', 'Composant', 'Profilé aluminium', 'ml', 9800),
  ('LIS-ALU-001', 'standard', 'Lisse / barreau aluminium', 'Composant', 'Profilé aluminium', 'ml', 4200),
  ('LIS-GI-012', 'standard', 'Lisse inox Ø12', 'Composant', 'Profilé aluminium', 'ml', 6800),
  ('P-SAB-001', 'standard', 'Sabot aluminium pour verre (profil U)', 'Composant', 'Profilé aluminium', 'ml', 45000),
  ('QUI-CAL-SAB', 'standard', 'Cale / kit de serrage de sabot', 'Composant', 'Quincaillerie', 'unite', 2800),
  ('SUP-MC-001', 'standard', 'Support de main courante murale inox', 'Composant', 'Quincaillerie', 'unite', 6500),
  ('QUI-EMB-MC', 'standard', 'Embout / coude de main courante', 'Composant', 'Quincaillerie', 'unite', 4500),
  ('FIX-ANG-001', 'standard', 'Fixation à l’anglaise (nez de dalle)', 'Composant', 'Visserie & fixations', 'unite', 7800),
  ('P-DOU-MUR', 'standard', 'Profil mural de paroi de douche', 'Composant', 'Profilé aluminium', 'ml', 9500),
  ('BAR-STA-INX', 'standard', 'Barre de stabilisation inox', 'Composant', 'Quincaillerie', 'unite', 22000),
  ('QUI-CHA-DOU', 'standard', 'Charnière verre-mur de douche inox', 'Composant', 'Quincaillerie', 'unite', 19000),
  ('QUI-POI-DOU', 'standard', 'Poignée de porte de douche', 'Composant', 'Quincaillerie', 'unite', 9500),
  ('P-DOU-RAIL', 'standard', 'Rail haut de douche coulissante inox', 'Composant', 'Profilé aluminium', 'ml', 28000),
  ('QUI-ROU-DOU', 'standard', 'Roulette de douche coulissante', 'Composant', 'Quincaillerie', 'unite', 8500),
  ('JNT-DOU-001', 'standard', 'Joint d’étanchéité de douche', 'Consommable', 'Joint & étanchéité', 'ml', 1800),
  ('ACM-004', 'standard', 'Panneau composite aluminium 4 mm (ACM)', 'Composant', 'Panneau', 'm2', 21000),
  ('P-OSS-OME', 'standard', 'Ossature oméga aluminium', 'Composant', 'Profilé aluminium', 'ml', 4800),
  ('FIX-EQU-ACM', 'standard', 'Équerre de fixation d’ossature', 'Composant', 'Visserie & fixations', 'unite', 1200),
  ('FIX-RIV-001', 'standard', 'Rivet / vis de cassette', 'Consommable', 'Visserie & fixations', 'unite', 120)
on conflict (code, standing) do nothing;
