-- ============================================================================
-- Sanix AluExpert ERP — Comptabilité SYSCOHADA révisé (Acte uniforme OHADA, 2017)
-- ============================================================================
-- 1. Plan comptable de référence SYSCOHADA révisé : comptes principaux (2 chiffres), divisionnaires
--    (3 chiffres) et sous-comptes utiles (4 chiffres), classes 1 à 8. L'arborescence se lit par PRÉFIXE :
--    le parent d'un compte est le plus long compte existant dont le code est un préfixe du sien
--    (401 → 4011 → 40110001…). Un compte qui a des sous-comptes est un compte de REGROUPEMENT :
--    il totalise ses sous-comptes et n'est plus imputable (contrôle en base, ci-dessous).
-- 2. Reprise du plan d'origine (codes à 6 chiffres 571000, 512000, 701000…) : chaque ancien compte est
--    fusionné dans son équivalent SYSCOHADA révisé (écritures, caisses, ventilations, règles et comptes par
--    défaut sont reportés), puis supprimé. Les comptes créés par l'entité (ex. 6042, 60420001) sont conservés.
-- 3. Comptes par défaut de la comptabilisation automatique ramenés sur les codes révisés.
-- Idempotent : peut être rejoué sans effet de bord.
-- ============================================================================
alter table public.compta_comptes add column if not exists standard boolean not null default false;
alter table public.caisses alter column compte_code set default '571';
alter table public.caisse_demandes add column if not exists compte_imputation text references public.compta_comptes(code);

-- 1. Plan de référence (le libellé d'un compte déjà présent n'est pas écrasé)
insert into public.compta_comptes (code, libelle, classe, nature, standard, actif) values
  ('10', 'Capital', 1, 'passif', true, true),
  ('101', 'Capital social', 1, 'passif', true, true),
  ('102', 'Capital par dotation', 1, 'passif', true, true),
  ('103', 'Capital personnel', 1, 'passif', true, true),
  ('104', 'Compte de l''exploitant', 1, 'passif', true, true),
  ('105', 'Primes liées au capital social', 1, 'passif', true, true),
  ('106', 'Écarts de réévaluation', 1, 'passif', true, true),
  ('109', 'Apporteurs, capital souscrit non appelé', 1, 'actif', true, true),
  ('11', 'Réserves', 1, 'passif', true, true),
  ('111', 'Réserve légale', 1, 'passif', true, true),
  ('112', 'Réserves statutaires ou contractuelles', 1, 'passif', true, true),
  ('113', 'Réserves réglementées', 1, 'passif', true, true),
  ('118', 'Autres réserves', 1, 'passif', true, true),
  ('12', 'Report à nouveau', 1, 'passif', true, true),
  ('121', 'Report à nouveau créditeur', 1, 'passif', true, true),
  ('129', 'Report à nouveau débiteur', 1, 'actif', true, true),
  ('13', 'Résultat net de l''exercice', 1, 'passif', true, true),
  ('130', 'Résultat en instance d''affectation', 1, 'passif', true, true),
  ('131', 'Résultat net : bénéfice', 1, 'passif', true, true),
  ('139', 'Résultat net : perte', 1, 'actif', true, true),
  ('14', 'Subventions d''investissement', 1, 'passif', true, true),
  ('141', 'Subventions d''équipement', 1, 'passif', true, true),
  ('148', 'Autres subventions d''investissement', 1, 'passif', true, true),
  ('15', 'Provisions réglementées et fonds assimilés', 1, 'passif', true, true),
  ('151', 'Amortissements dérogatoires', 1, 'passif', true, true),
  ('158', 'Autres provisions et fonds réglementés', 1, 'passif', true, true),
  ('16', 'Emprunts et dettes assimilées', 1, 'passif', true, true),
  ('161', 'Emprunts obligataires', 1, 'passif', true, true),
  ('162', 'Emprunts et dettes auprès des établissements de crédit', 1, 'passif', true, true),
  ('163', 'Avances reçues de l''État', 1, 'passif', true, true),
  ('164', 'Avances reçues et comptes courants bloqués', 1, 'passif', true, true),
  ('165', 'Dépôts et cautionnements reçus', 1, 'passif', true, true),
  ('166', 'Intérêts courus', 1, 'passif', true, true),
  ('167', 'Avances assorties de conditions particulières', 1, 'passif', true, true),
  ('168', 'Autres emprunts et dettes', 1, 'passif', true, true),
  ('17', 'Dettes de location-acquisition', 1, 'passif', true, true),
  ('172', 'Dettes de location-acquisition / crédit-bail immobilier', 1, 'passif', true, true),
  ('173', 'Dettes de location-acquisition / crédit-bail mobilier', 1, 'passif', true, true),
  ('176', 'Intérêts courus sur dettes de location-acquisition', 1, 'passif', true, true),
  ('178', 'Autres dettes de location-acquisition', 1, 'passif', true, true),
  ('18', 'Dettes liées à des participations et comptes de liaison', 1, 'passif', true, true),
  ('181', 'Dettes liées à des participations', 1, 'passif', true, true),
  ('184', 'Comptes permanents bloqués des établissements et succursales', 1, 'passif', true, true),
  ('185', 'Comptes permanents non bloqués des établissements et succursales', 1, 'passif', true, true),
  ('19', 'Provisions pour risques et charges', 1, 'passif', true, true),
  ('191', 'Provisions pour litiges', 1, 'passif', true, true),
  ('194', 'Provisions pour pertes de change', 1, 'passif', true, true),
  ('195', 'Provisions pour impôts', 1, 'passif', true, true),
  ('196', 'Provisions pour pensions et obligations similaires', 1, 'passif', true, true),
  ('198', 'Autres provisions pour risques et charges', 1, 'passif', true, true),
  ('21', 'Immobilisations incorporelles', 2, 'actif', true, true),
  ('211', 'Frais de développement', 2, 'actif', true, true),
  ('212', 'Brevets, licences, concessions et droits similaires', 2, 'actif', true, true),
  ('213', 'Logiciels et sites internet', 2, 'actif', true, true),
  ('214', 'Marques', 2, 'actif', true, true),
  ('215', 'Fonds commercial', 2, 'actif', true, true),
  ('216', 'Droit au bail', 2, 'actif', true, true),
  ('217', 'Investissements de création', 2, 'actif', true, true),
  ('218', 'Autres droits et valeurs incorporels', 2, 'actif', true, true),
  ('219', 'Immobilisations incorporelles en cours', 2, 'actif', true, true),
  ('22', 'Terrains', 2, 'actif', true, true),
  ('221', 'Terrains agricoles et forestiers', 2, 'actif', true, true),
  ('222', 'Terrains nus', 2, 'actif', true, true),
  ('223', 'Terrains bâtis', 2, 'actif', true, true),
  ('224', 'Travaux de mise en valeur des terrains', 2, 'actif', true, true),
  ('225', 'Terrains de carrières – tréfonds', 2, 'actif', true, true),
  ('226', 'Terrains aménagés', 2, 'actif', true, true),
  ('227', 'Terrains mis en concession', 2, 'actif', true, true),
  ('228', 'Autres terrains', 2, 'actif', true, true),
  ('229', 'Aménagements de terrains en cours', 2, 'actif', true, true),
  ('23', 'Bâtiments, installations techniques et agencements', 2, 'actif', true, true),
  ('231', 'Bâtiments industriels, agricoles, administratifs et commerciaux sur sol propre', 2, 'actif', true, true),
  ('232', 'Bâtiments industriels, agricoles, administratifs et commerciaux sur sol d''autrui', 2, 'actif', true, true),
  ('233', 'Ouvrages d''infrastructure', 2, 'actif', true, true),
  ('234', 'Aménagements, agencements et installations techniques', 2, 'actif', true, true),
  ('235', 'Aménagements de bureaux', 2, 'actif', true, true),
  ('237', 'Bâtiments industriels, agricoles et commerciaux mis en concession', 2, 'actif', true, true),
  ('238', 'Autres installations et agencements', 2, 'actif', true, true),
  ('239', 'Bâtiments et installations en cours', 2, 'actif', true, true),
  ('24', 'Matériel, mobilier et actifs biologiques', 2, 'actif', true, true),
  ('241', 'Matériel et outillage industriel et commercial', 2, 'actif', true, true),
  ('242', 'Matériel et outillage agricole', 2, 'actif', true, true),
  ('243', 'Matériel d''emballage récupérable et identifiable', 2, 'actif', true, true),
  ('244', 'Matériel et mobilier', 2, 'actif', true, true),
  ('245', 'Matériel de transport', 2, 'actif', true, true),
  ('246', 'Actifs biologiques', 2, 'actif', true, true),
  ('247', 'Agencements, aménagements du matériel et des actifs biologiques', 2, 'actif', true, true),
  ('248', 'Autres matériels et mobiliers', 2, 'actif', true, true),
  ('249', 'Matériels et actifs biologiques en cours', 2, 'actif', true, true),
  ('25', 'Avances et acomptes versés sur immobilisations', 2, 'actif', true, true),
  ('251', 'Avances et acomptes versés sur immobilisations incorporelles', 2, 'actif', true, true),
  ('252', 'Avances et acomptes versés sur immobilisations corporelles', 2, 'actif', true, true),
  ('26', 'Titres de participation', 2, 'actif', true, true),
  ('261', 'Titres de participation dans des sociétés sous contrôle exclusif', 2, 'actif', true, true),
  ('262', 'Titres de participation dans des sociétés sous contrôle conjoint', 2, 'actif', true, true),
  ('263', 'Titres de participation dans des sociétés conférant une influence notable', 2, 'actif', true, true),
  ('265', 'Participations dans des organismes professionnels', 2, 'actif', true, true),
  ('266', 'Parts dans des groupements d''intérêt économique (GIE)', 2, 'actif', true, true),
  ('268', 'Autres titres de participation', 2, 'actif', true, true),
  ('27', 'Autres immobilisations financières', 2, 'actif', true, true),
  ('271', 'Prêts et créances', 2, 'actif', true, true),
  ('272', 'Prêts au personnel', 2, 'actif', true, true),
  ('273', 'Créances sur l''État', 2, 'actif', true, true),
  ('274', 'Titres immobilisés', 2, 'actif', true, true),
  ('275', 'Dépôts et cautionnements versés', 2, 'actif', true, true),
  ('276', 'Intérêts courus', 2, 'actif', true, true),
  ('277', 'Créances rattachées à des participations et avances à des GIE', 2, 'actif', true, true),
  ('278', 'Immobilisations financières diverses', 2, 'actif', true, true),
  ('28', 'Amortissements', 2, 'actif', true, true),
  ('281', 'Amortissements des immobilisations incorporelles', 2, 'actif', true, true),
  ('2813', 'Amortissements des logiciels et sites internet', 2, 'actif', true, true),
  ('282', 'Amortissements des terrains', 2, 'actif', true, true),
  ('283', 'Amortissements des bâtiments, installations techniques et agencements', 2, 'actif', true, true),
  ('2831', 'Amortissements des bâtiments sur sol propre', 2, 'actif', true, true),
  ('284', 'Amortissements du matériel, du mobilier et des actifs biologiques', 2, 'actif', true, true),
  ('2841', 'Amortissements du matériel et outillage industriel et commercial', 2, 'actif', true, true),
  ('2844', 'Amortissements du matériel et mobilier', 2, 'actif', true, true),
  ('2845', 'Amortissements du matériel de transport', 2, 'actif', true, true),
  ('29', 'Dépréciations des immobilisations', 2, 'actif', true, true),
  ('291', 'Dépréciations des immobilisations incorporelles', 2, 'actif', true, true),
  ('292', 'Dépréciations des terrains', 2, 'actif', true, true),
  ('293', 'Dépréciations des bâtiments, installations techniques et agencements', 2, 'actif', true, true),
  ('294', 'Dépréciations du matériel, du mobilier et des actifs biologiques', 2, 'actif', true, true),
  ('295', 'Dépréciations des avances et acomptes versés sur immobilisations', 2, 'actif', true, true),
  ('296', 'Dépréciations des titres de participation', 2, 'actif', true, true),
  ('297', 'Dépréciations des autres immobilisations financières', 2, 'actif', true, true),
  ('31', 'Marchandises', 3, 'actif', true, true),
  ('311', 'Marchandises A', 3, 'actif', true, true),
  ('312', 'Marchandises B', 3, 'actif', true, true),
  ('318', 'Marchandises hors activités ordinaires (HAO)', 3, 'actif', true, true),
  ('32', 'Matières premières et fournitures liées', 3, 'actif', true, true),
  ('321', 'Matières A', 3, 'actif', true, true),
  ('322', 'Matières B', 3, 'actif', true, true),
  ('323', 'Fournitures (A, B)', 3, 'actif', true, true),
  ('33', 'Autres approvisionnements', 3, 'actif', true, true),
  ('331', 'Matières consommables', 3, 'actif', true, true),
  ('332', 'Matières combustibles', 3, 'actif', true, true),
  ('333', 'Produits d''entretien', 3, 'actif', true, true),
  ('334', 'Fournitures d''atelier et d''usine', 3, 'actif', true, true),
  ('335', 'Emballages', 3, 'actif', true, true),
  ('336', 'Fournitures de magasin', 3, 'actif', true, true),
  ('337', 'Fournitures de bureau', 3, 'actif', true, true),
  ('338', 'Autres matières', 3, 'actif', true, true),
  ('34', 'Produits en cours', 3, 'actif', true, true),
  ('341', 'Produits en cours', 3, 'actif', true, true),
  ('342', 'Travaux en cours', 3, 'actif', true, true),
  ('35', 'Services en cours', 3, 'actif', true, true),
  ('351', 'Études en cours', 3, 'actif', true, true),
  ('352', 'Prestations de services en cours', 3, 'actif', true, true),
  ('36', 'Produits finis', 3, 'actif', true, true),
  ('361', 'Produits finis A', 3, 'actif', true, true),
  ('362', 'Produits finis B', 3, 'actif', true, true),
  ('37', 'Produits intermédiaires et résiduels', 3, 'actif', true, true),
  ('371', 'Produits intermédiaires', 3, 'actif', true, true),
  ('372', 'Produits résiduels', 3, 'actif', true, true),
  ('38', 'Stocks en cours de route, en consignation ou en dépôt', 3, 'actif', true, true),
  ('381', 'Marchandises en cours de route', 3, 'actif', true, true),
  ('382', 'Matières premières et fournitures liées en cours de route', 3, 'actif', true, true),
  ('383', 'Autres approvisionnements en cours de route', 3, 'actif', true, true),
  ('386', 'Produits finis en cours de route', 3, 'actif', true, true),
  ('387', 'Stocks en consignation ou en dépôt', 3, 'actif', true, true),
  ('39', 'Dépréciations des stocks et encours de production', 3, 'actif', true, true),
  ('391', 'Dépréciations des stocks de marchandises', 3, 'actif', true, true),
  ('392', 'Dépréciations des stocks de matières premières et fournitures liées', 3, 'actif', true, true),
  ('393', 'Dépréciations des stocks d''autres approvisionnements', 3, 'actif', true, true),
  ('394', 'Dépréciations des productions en cours', 3, 'actif', true, true),
  ('396', 'Dépréciations des stocks de produits finis', 3, 'actif', true, true),
  ('40', 'Fournisseurs et comptes rattachés', 4, 'passif', true, true),
  ('401', 'Fournisseurs, dettes en compte', 4, 'passif', true, true),
  ('4011', 'Fournisseurs', 4, 'passif', true, true),
  ('4012', 'Fournisseurs groupe', 4, 'passif', true, true),
  ('4013', 'Fournisseurs sous-traitants', 4, 'passif', true, true),
  ('4016', 'Fournisseurs, réserve de propriété', 4, 'passif', true, true),
  ('4017', 'Fournisseurs, retenues de garantie', 4, 'passif', true, true),
  ('402', 'Fournisseurs, effets à payer', 4, 'passif', true, true),
  ('404', 'Fournisseurs, acquisitions courantes d''immobilisations', 4, 'passif', true, true),
  ('408', 'Fournisseurs, factures non parvenues', 4, 'passif', true, true),
  ('409', 'Fournisseurs débiteurs', 4, 'actif', true, true),
  ('4091', 'Fournisseurs, avances et acomptes versés', 4, 'actif', true, true),
  ('4094', 'Fournisseurs, créances pour emballages et matériels à rendre', 4, 'actif', true, true),
  ('4098', 'Fournisseurs, rabais, remises, ristournes et autres avoirs à obtenir', 4, 'actif', true, true),
  ('41', 'Clients et comptes rattachés', 4, 'actif', true, true),
  ('411', 'Clients', 4, 'actif', true, true),
  ('4111', 'Clients', 4, 'actif', true, true),
  ('4112', 'Clients groupe', 4, 'actif', true, true),
  ('4114', 'Clients, État et collectivités publiques', 4, 'actif', true, true),
  ('4117', 'Clients, retenues de garantie', 4, 'actif', true, true),
  ('412', 'Clients, effets à recevoir en portefeuille', 4, 'actif', true, true),
  ('414', 'Créances sur cessions courantes d''immobilisations', 4, 'actif', true, true),
  ('415', 'Clients, effets escomptés non échus', 4, 'actif', true, true),
  ('416', 'Créances clients litigieuses ou douteuses', 4, 'actif', true, true),
  ('418', 'Clients, produits à recevoir', 4, 'actif', true, true),
  ('419', 'Clients créditeurs', 4, 'passif', true, true),
  ('4191', 'Clients, avances et acomptes reçus', 4, 'passif', true, true),
  ('4194', 'Clients, dettes pour emballages et matériels consignés', 4, 'passif', true, true),
  ('4198', 'Clients, rabais, remises, ristournes et autres avoirs à accorder', 4, 'passif', true, true),
  ('42', 'Personnel', 4, 'passif', true, true),
  ('421', 'Personnel, avances et acomptes', 4, 'actif', true, true),
  ('422', 'Personnel, rémunérations dues', 4, 'passif', true, true),
  ('423', 'Personnel, oppositions, saisies-arrêts', 4, 'passif', true, true),
  ('424', 'Personnel, œuvres sociales internes', 4, 'passif', true, true),
  ('425', 'Représentants du personnel', 4, 'passif', true, true),
  ('426', 'Personnel, participation aux bénéfices', 4, 'passif', true, true),
  ('427', 'Personnel, dépôts', 4, 'passif', true, true),
  ('428', 'Personnel, charges à payer et produits à recevoir', 4, 'passif', true, true),
  ('43', 'Organismes sociaux', 4, 'passif', true, true),
  ('431', 'Sécurité sociale (CNPS)', 4, 'passif', true, true),
  ('432', 'Caisses de retraite complémentaire', 4, 'passif', true, true),
  ('433', 'Autres organismes sociaux', 4, 'passif', true, true),
  ('438', 'Organismes sociaux, charges à payer et produits à recevoir', 4, 'passif', true, true),
  ('44', 'État et collectivités publiques', 4, 'passif', true, true),
  ('441', 'État, impôt sur les bénéfices', 4, 'passif', true, true),
  ('442', 'État, autres impôts et taxes', 4, 'passif', true, true),
  ('443', 'État, TVA facturée', 4, 'passif', true, true),
  ('4431', 'TVA facturée sur ventes', 4, 'passif', true, true),
  ('4432', 'TVA facturée sur prestations de services', 4, 'passif', true, true),
  ('4433', 'TVA facturée sur travaux', 4, 'passif', true, true),
  ('4434', 'TVA facturée sur production livrée à soi-même', 4, 'passif', true, true),
  ('4435', 'TVA sur factures à établir', 4, 'passif', true, true),
  ('444', 'État, TVA due ou crédit de TVA', 4, 'passif', true, true),
  ('4441', 'État, TVA due', 4, 'passif', true, true),
  ('4449', 'État, crédit de TVA à reporter', 4, 'actif', true, true),
  ('445', 'État, TVA récupérable', 4, 'actif', true, true),
  ('4451', 'TVA récupérable sur immobilisations', 4, 'actif', true, true),
  ('4452', 'TVA récupérable sur achats', 4, 'actif', true, true),
  ('4453', 'TVA récupérable sur transport', 4, 'actif', true, true),
  ('4454', 'TVA récupérable sur services extérieurs et autres charges', 4, 'actif', true, true),
  ('4455', 'TVA récupérable sur factures non parvenues', 4, 'actif', true, true),
  ('4456', 'TVA transférée par d''autres entités', 4, 'actif', true, true),
  ('446', 'État, autres taxes sur le chiffre d''affaires', 4, 'passif', true, true),
  ('447', 'État, impôts retenus à la source', 4, 'passif', true, true),
  ('448', 'État, charges à payer et produits à recevoir', 4, 'autre', true, true),
  ('449', 'État, créances et dettes diverses', 4, 'autre', true, true),
  ('45', 'Organismes internationaux', 4, 'autre', true, true),
  ('451', 'Opérations avec les organismes africains', 4, 'autre', true, true),
  ('452', 'Opérations avec les autres organismes internationaux', 4, 'autre', true, true),
  ('458', 'Organismes internationaux, fonds de dotation et subventions à recevoir', 4, 'actif', true, true),
  ('46', 'Apporteurs, associés et groupe', 4, 'autre', true, true),
  ('461', 'Apporteurs, opérations sur le capital', 4, 'autre', true, true),
  ('462', 'Associés, comptes courants', 4, 'autre', true, true),
  ('463', 'Associés, opérations faites en commun', 4, 'autre', true, true),
  ('465', 'Associés, dividendes à payer', 4, 'autre', true, true),
  ('466', 'Groupe, comptes courants', 4, 'autre', true, true),
  ('467', 'Apporteurs, restant dû sur capital appelé', 4, 'actif', true, true),
  ('47', 'Débiteurs et créditeurs divers', 4, 'autre', true, true),
  ('471', 'Débiteurs et créditeurs divers', 4, 'autre', true, true),
  ('472', 'Créances et dettes sur titres de placement', 4, 'autre', true, true),
  ('474', 'Répartition périodique des charges et des produits', 4, 'autre', true, true),
  ('475', 'Créances sur travaux non encore facturables', 4, 'actif', true, true),
  ('476', 'Charges constatées d''avance', 4, 'actif', true, true),
  ('477', 'Produits constatés d''avance', 4, 'autre', true, true),
  ('478', 'Écarts de conversion – Actif', 4, 'actif', true, true),
  ('479', 'Écarts de conversion – Passif', 4, 'autre', true, true),
  ('48', 'Créances et dettes hors activités ordinaires (HAO)', 4, 'passif', true, true),
  ('481', 'Fournisseurs d''investissements', 4, 'passif', true, true),
  ('482', 'Fournisseurs d''investissements, effets à payer', 4, 'passif', true, true),
  ('484', 'Autres dettes hors activités ordinaires', 4, 'passif', true, true),
  ('485', 'Créances sur cessions d''immobilisations', 4, 'actif', true, true),
  ('488', 'Autres créances hors activités ordinaires', 4, 'actif', true, true),
  ('49', 'Dépréciations et provisions pour risques à court terme (tiers)', 4, 'actif', true, true),
  ('490', 'Dépréciations des comptes fournisseurs', 4, 'actif', true, true),
  ('491', 'Dépréciations des comptes clients', 4, 'actif', true, true),
  ('492', 'Dépréciations des comptes personnel', 4, 'actif', true, true),
  ('493', 'Dépréciations des comptes organismes sociaux', 4, 'actif', true, true),
  ('494', 'Dépréciations des comptes État et collectivités publiques', 4, 'actif', true, true),
  ('495', 'Dépréciations des comptes organismes internationaux', 4, 'actif', true, true),
  ('496', 'Dépréciations des comptes apporteurs, associés et groupe', 4, 'actif', true, true),
  ('497', 'Dépréciations des comptes débiteurs divers', 4, 'actif', true, true),
  ('498', 'Dépréciations des comptes de créances HAO', 4, 'actif', true, true),
  ('499', 'Provisions pour risques à court terme', 4, 'actif', true, true),
  ('50', 'Titres de placement', 5, 'actif', true, true),
  ('501', 'Titres du Trésor et bons de caisse à court terme', 5, 'actif', true, true),
  ('502', 'Actions', 5, 'actif', true, true),
  ('503', 'Obligations', 5, 'actif', true, true),
  ('504', 'Bons de souscription', 5, 'actif', true, true),
  ('505', 'Titres négociables hors région', 5, 'actif', true, true),
  ('506', 'Intérêts courus', 5, 'actif', true, true),
  ('508', 'Autres titres de placement et créances assimilées', 5, 'actif', true, true),
  ('51', 'Valeurs à encaisser', 5, 'actif', true, true),
  ('511', 'Effets à encaisser', 5, 'actif', true, true),
  ('512', 'Effets à l''encaissement', 5, 'actif', true, true),
  ('513', 'Chèques à encaisser', 5, 'actif', true, true),
  ('514', 'Chèques à l''encaissement', 5, 'actif', true, true),
  ('515', 'Cartes de crédit à encaisser', 5, 'actif', true, true),
  ('518', 'Autres valeurs à l''encaissement', 5, 'actif', true, true),
  ('52', 'Banques', 5, 'actif', true, true),
  ('521', 'Banques locales', 5, 'actif', true, true),
  ('522', 'Banques autres États de la région', 5, 'actif', true, true),
  ('523', 'Banques autres États de la zone monétaire', 5, 'actif', true, true),
  ('524', 'Banques hors zone monétaire', 5, 'actif', true, true),
  ('525', 'Banques, dépôts à terme', 5, 'actif', true, true),
  ('526', 'Banques, intérêts courus', 5, 'actif', true, true),
  ('53', 'Établissements financiers et assimilés', 5, 'actif', true, true),
  ('531', 'Chèques postaux', 5, 'actif', true, true),
  ('532', 'Trésor', 5, 'actif', true, true),
  ('533', 'Sociétés de gestion et d''intermédiation (SGI)', 5, 'actif', true, true),
  ('536', 'Établissements financiers', 5, 'actif', true, true),
  ('538', 'Autres organismes financiers', 5, 'actif', true, true),
  ('54', 'Instruments de trésorerie', 5, 'actif', true, true),
  ('541', 'Options de taux d''intérêt', 5, 'actif', true, true),
  ('542', 'Options de taux de change', 5, 'actif', true, true),
  ('543', 'Options de taux boursiers', 5, 'actif', true, true),
  ('544', 'Instruments de marchés à terme', 5, 'actif', true, true),
  ('545', 'Avoirs d''or et autres métaux précieux', 5, 'actif', true, true),
  ('55', 'Instruments de monnaie électronique', 5, 'actif', true, true),
  ('551', 'Monnaie électronique carte carburant', 5, 'actif', true, true),
  ('552', 'Monnaie électronique téléphone portable (Mobile Money)', 5, 'actif', true, true),
  ('553', 'Monnaie électronique carte péage', 5, 'actif', true, true),
  ('554', 'Porte-monnaie électronique', 5, 'actif', true, true),
  ('558', 'Autres instruments de monnaie électronique', 5, 'actif', true, true),
  ('56', 'Banques, crédits de trésorerie et d''escompte', 5, 'passif', true, true),
  ('561', 'Crédits de trésorerie', 5, 'passif', true, true),
  ('564', 'Escompte de crédits de campagne', 5, 'passif', true, true),
  ('565', 'Escompte de crédits ordinaires', 5, 'passif', true, true),
  ('566', 'Banques, crédits de trésorerie, intérêts courus', 5, 'passif', true, true),
  ('57', 'Caisse', 5, 'actif', true, true),
  ('571', 'Caisse siège social', 5, 'actif', true, true),
  ('572', 'Caisse succursale A', 5, 'actif', true, true),
  ('573', 'Caisse succursale B', 5, 'actif', true, true),
  ('58', 'Régies d''avances, accréditifs et virements internes', 5, 'actif', true, true),
  ('581', 'Régies d''avance', 5, 'actif', true, true),
  ('582', 'Accréditifs', 5, 'actif', true, true),
  ('585', 'Virements de fonds', 5, 'autre', true, true),
  ('588', 'Autres virements internes', 5, 'autre', true, true),
  ('59', 'Dépréciations et provisions pour risques à court terme (trésorerie)', 5, 'actif', true, true),
  ('590', 'Dépréciations des titres de placement', 5, 'actif', true, true),
  ('591', 'Dépréciations des titres et valeurs à encaisser', 5, 'actif', true, true),
  ('592', 'Dépréciations des comptes banques', 5, 'actif', true, true),
  ('593', 'Dépréciations des comptes établissements financiers', 5, 'actif', true, true),
  ('594', 'Dépréciations des comptes d''instruments de trésorerie', 5, 'actif', true, true),
  ('599', 'Provisions pour risques à court terme à caractère financier', 5, 'passif', true, true),
  ('60', 'Achats et variations de stocks', 6, 'charge', true, true),
  ('601', 'Achats de marchandises', 6, 'charge', true, true),
  ('602', 'Achats de matières premières et fournitures liées', 6, 'charge', true, true),
  ('603', 'Variations des stocks de biens achetés', 6, 'charge', true, true),
  ('6031', 'Variations des stocks de marchandises', 6, 'charge', true, true),
  ('6032', 'Variations des stocks de matières premières et fournitures liées', 6, 'charge', true, true),
  ('6033', 'Variations des stocks d''autres approvisionnements', 6, 'charge', true, true),
  ('604', 'Achats stockés de matières et fournitures consommables', 6, 'charge', true, true),
  ('6041', 'Matières consommables', 6, 'charge', true, true),
  ('6042', 'Matières combustibles', 6, 'charge', true, true),
  ('6043', 'Produits d''entretien', 6, 'charge', true, true),
  ('6044', 'Fournitures d''atelier et d''usine', 6, 'charge', true, true),
  ('6046', 'Fournitures de magasin', 6, 'charge', true, true),
  ('6047', 'Fournitures de bureau', 6, 'charge', true, true),
  ('605', 'Autres achats', 6, 'charge', true, true),
  ('6051', 'Fournitures non stockables – Eau', 6, 'charge', true, true),
  ('6052', 'Fournitures non stockables – Électricité', 6, 'charge', true, true),
  ('6053', 'Fournitures non stockables – Autres énergies', 6, 'charge', true, true),
  ('6054', 'Fournitures d''entretien non stockables', 6, 'charge', true, true),
  ('6055', 'Fournitures de bureau non stockables', 6, 'charge', true, true),
  ('6056', 'Achats de petit matériel et outillage', 6, 'charge', true, true),
  ('6057', 'Achats d''études et prestations de services', 6, 'charge', true, true),
  ('6058', 'Achats de travaux, matériels et équipements', 6, 'charge', true, true),
  ('608', 'Achats d''emballages', 6, 'charge', true, true),
  ('61', 'Transports', 6, 'charge', true, true),
  ('611', 'Transports sur achats', 6, 'charge', true, true),
  ('612', 'Transports sur ventes', 6, 'charge', true, true),
  ('613', 'Transports pour le compte de tiers', 6, 'charge', true, true),
  ('614', 'Transports du personnel', 6, 'charge', true, true),
  ('616', 'Transports de plis', 6, 'charge', true, true),
  ('618', 'Autres frais de transport', 6, 'charge', true, true),
  ('6181', 'Voyages et déplacements', 6, 'charge', true, true),
  ('6182', 'Transports entre établissements ou chantiers', 6, 'charge', true, true),
  ('6183', 'Transports administratifs', 6, 'charge', true, true),
  ('62', 'Services extérieurs', 6, 'charge', true, true),
  ('621', 'Sous-traitance générale', 6, 'charge', true, true),
  ('622', 'Locations et charges locatives', 6, 'charge', true, true),
  ('623', 'Redevances de location-acquisition', 6, 'charge', true, true),
  ('624', 'Entretien, réparations, remise en état et maintenance', 6, 'charge', true, true),
  ('625', 'Primes d''assurance', 6, 'charge', true, true),
  ('626', 'Études, recherches et documentation', 6, 'charge', true, true),
  ('627', 'Publicité, publications, relations publiques', 6, 'charge', true, true),
  ('628', 'Frais de télécommunications', 6, 'charge', true, true),
  ('63', 'Autres services extérieurs', 6, 'charge', true, true),
  ('631', 'Frais bancaires', 6, 'charge', true, true),
  ('632', 'Rémunérations d''intermédiaires et de conseils', 6, 'charge', true, true),
  ('633', 'Frais de formation du personnel', 6, 'charge', true, true),
  ('634', 'Redevances pour brevets, licences, logiciels, concessions et droits similaires', 6, 'charge', true, true),
  ('635', 'Cotisations', 6, 'charge', true, true),
  ('637', 'Rémunérations de personnel extérieur à l''entité', 6, 'charge', true, true),
  ('638', 'Autres charges externes', 6, 'charge', true, true),
  ('64', 'Impôts et taxes', 6, 'charge', true, true),
  ('641', 'Impôts et taxes directs', 6, 'charge', true, true),
  ('645', 'Impôts et taxes indirects', 6, 'charge', true, true),
  ('646', 'Droits d''enregistrement', 6, 'charge', true, true),
  ('647', 'Pénalités, amendes fiscales', 6, 'charge', true, true),
  ('648', 'Autres impôts et taxes', 6, 'charge', true, true),
  ('65', 'Autres charges', 6, 'charge', true, true),
  ('651', 'Pertes sur créances clients et autres débiteurs', 6, 'charge', true, true),
  ('652', 'Quote-part de résultat sur opérations faites en commun', 6, 'charge', true, true),
  ('654', 'Valeurs comptables des cessions courantes d''immobilisations', 6, 'charge', true, true),
  ('656', 'Pertes de change sur créances et dettes commerciales', 6, 'charge', true, true),
  ('657', 'Pénalités et amendes pénales', 6, 'charge', true, true),
  ('658', 'Charges diverses', 6, 'charge', true, true),
  ('659', 'Charges pour dépréciations et provisions pour risques à court terme d''exploitation', 6, 'charge', true, true),
  ('66', 'Charges de personnel', 6, 'charge', true, true),
  ('661', 'Rémunérations directes versées au personnel national', 6, 'charge', true, true),
  ('662', 'Rémunérations directes versées au personnel non national', 6, 'charge', true, true),
  ('663', 'Indemnités forfaitaires versées au personnel', 6, 'charge', true, true),
  ('664', 'Charges sociales', 6, 'charge', true, true),
  ('666', 'Rémunérations et charges sociales de l''exploitant individuel', 6, 'charge', true, true),
  ('667', 'Rémunération transférée de personnel extérieur', 6, 'charge', true, true),
  ('668', 'Autres charges sociales', 6, 'charge', true, true),
  ('67', 'Frais financiers et charges assimilées', 6, 'charge', true, true),
  ('671', 'Intérêts des emprunts', 6, 'charge', true, true),
  ('672', 'Intérêts dans loyers de location-acquisition', 6, 'charge', true, true),
  ('673', 'Escomptes accordés', 6, 'charge', true, true),
  ('674', 'Autres intérêts', 6, 'charge', true, true),
  ('675', 'Escomptes des effets de commerce', 6, 'charge', true, true),
  ('676', 'Pertes de change financières', 6, 'charge', true, true),
  ('677', 'Pertes sur cessions de titres de placement', 6, 'charge', true, true),
  ('678', 'Pertes sur risques financiers', 6, 'charge', true, true),
  ('679', 'Charges pour dépréciations et provisions pour risques à court terme financières', 6, 'charge', true, true),
  ('68', 'Dotations aux amortissements', 6, 'charge', true, true),
  ('681', 'Dotations aux amortissements d''exploitation', 6, 'charge', true, true),
  ('69', 'Dotations aux provisions et aux dépréciations', 6, 'charge', true, true),
  ('691', 'Dotations aux provisions et aux dépréciations d''exploitation', 6, 'charge', true, true),
  ('697', 'Dotations aux provisions et aux dépréciations financières', 6, 'charge', true, true),
  ('70', 'Ventes', 7, 'produit', true, true),
  ('701', 'Ventes de marchandises', 7, 'produit', true, true),
  ('702', 'Ventes de produits finis', 7, 'produit', true, true),
  ('703', 'Ventes de produits intermédiaires', 7, 'produit', true, true),
  ('704', 'Ventes de produits résiduels', 7, 'produit', true, true),
  ('705', 'Travaux facturés', 7, 'produit', true, true),
  ('706', 'Services vendus', 7, 'produit', true, true),
  ('707', 'Produits accessoires', 7, 'produit', true, true),
  ('71', 'Subventions d''exploitation', 7, 'produit', true, true),
  ('711', 'Subventions sur produits à l''exportation', 7, 'produit', true, true),
  ('712', 'Subventions sur produits à l''importation', 7, 'produit', true, true),
  ('713', 'Subventions sur produits de péréquation', 7, 'produit', true, true),
  ('718', 'Autres subventions d''exploitation', 7, 'produit', true, true),
  ('72', 'Production immobilisée', 7, 'produit', true, true),
  ('721', 'Immobilisations incorporelles', 7, 'produit', true, true),
  ('722', 'Immobilisations corporelles', 7, 'produit', true, true),
  ('726', 'Immobilisations financières', 7, 'produit', true, true),
  ('73', 'Variations des stocks de biens et de services produits', 7, 'produit', true, true),
  ('734', 'Variations des stocks de produits en cours', 7, 'produit', true, true),
  ('735', 'Variations des en-cours de services', 7, 'produit', true, true),
  ('736', 'Variations des stocks de produits finis', 7, 'produit', true, true),
  ('737', 'Variations des stocks de produits intermédiaires et résiduels', 7, 'produit', true, true),
  ('75', 'Autres produits', 7, 'produit', true, true),
  ('751', 'Profits sur créances clients et autres débiteurs', 7, 'produit', true, true),
  ('752', 'Quote-part de résultat sur opérations faites en commun', 7, 'produit', true, true),
  ('754', 'Produits des cessions courantes d''immobilisations', 7, 'produit', true, true),
  ('756', 'Gains de change sur créances et dettes commerciales', 7, 'produit', true, true),
  ('758', 'Produits divers', 7, 'produit', true, true),
  ('759', 'Reprises de charges pour dépréciations et provisions pour risques à court terme d''exploitation', 7, 'produit', true, true),
  ('77', 'Revenus financiers et produits assimilés', 7, 'produit', true, true),
  ('771', 'Intérêts de prêts et créances diverses', 7, 'produit', true, true),
  ('772', 'Revenus de participations et autres titres immobilisés', 7, 'produit', true, true),
  ('773', 'Escomptes obtenus', 7, 'produit', true, true),
  ('774', 'Revenus de placement', 7, 'produit', true, true),
  ('775', 'Intérêts dans loyers de location-acquisition', 7, 'produit', true, true),
  ('776', 'Gains de change financiers', 7, 'produit', true, true),
  ('777', 'Gains sur cessions de titres de placement', 7, 'produit', true, true),
  ('778', 'Gains sur risques financiers', 7, 'produit', true, true),
  ('779', 'Reprises de charges pour dépréciations et provisions pour risques à court terme financières', 7, 'produit', true, true),
  ('78', 'Transferts de charges', 7, 'produit', true, true),
  ('781', 'Transferts de charges d''exploitation', 7, 'produit', true, true),
  ('787', 'Transferts de charges financières', 7, 'produit', true, true),
  ('79', 'Reprises de provisions, de dépréciations et autres', 7, 'produit', true, true),
  ('791', 'Reprises de provisions et dépréciations d''exploitation', 7, 'produit', true, true),
  ('797', 'Reprises de provisions et dépréciations financières', 7, 'produit', true, true),
  ('798', 'Reprises d''amortissements', 7, 'produit', true, true),
  ('799', 'Reprises de subventions d''investissement', 7, 'produit', true, true),
  ('81', 'Valeurs comptables des cessions d''immobilisations', 8, 'charge', true, true),
  ('811', 'Immobilisations incorporelles', 8, 'charge', true, true),
  ('812', 'Immobilisations corporelles', 8, 'charge', true, true),
  ('816', 'Immobilisations financières', 8, 'charge', true, true),
  ('82', 'Produits des cessions d''immobilisations', 8, 'produit', true, true),
  ('821', 'Immobilisations incorporelles', 8, 'produit', true, true),
  ('822', 'Immobilisations corporelles', 8, 'produit', true, true),
  ('826', 'Immobilisations financières', 8, 'produit', true, true),
  ('83', 'Charges hors activités ordinaires', 8, 'charge', true, true),
  ('831', 'Charges HAO constatées', 8, 'charge', true, true),
  ('834', 'Pertes sur créances HAO', 8, 'charge', true, true),
  ('835', 'Dons et libéralités accordés', 8, 'charge', true, true),
  ('836', 'Abandons de créances consentis', 8, 'charge', true, true),
  ('839', 'Charges pour dépréciations et provisions pour risques à court terme HAO', 8, 'charge', true, true),
  ('84', 'Produits hors activités ordinaires', 8, 'produit', true, true),
  ('841', 'Produits HAO constatés', 8, 'produit', true, true),
  ('845', 'Dons et libéralités obtenus', 8, 'produit', true, true),
  ('846', 'Abandons de créances obtenus', 8, 'produit', true, true),
  ('848', 'Transferts de charges HAO', 8, 'produit', true, true),
  ('849', 'Reprises de charges pour dépréciations et provisions pour risques à court terme HAO', 8, 'produit', true, true),
  ('85', 'Dotations hors activités ordinaires', 8, 'charge', true, true),
  ('851', 'Dotations aux provisions réglementées', 8, 'charge', true, true),
  ('852', 'Dotations aux amortissements HAO', 8, 'charge', true, true),
  ('853', 'Dotations aux dépréciations HAO', 8, 'charge', true, true),
  ('854', 'Dotations aux provisions pour risques et charges HAO', 8, 'charge', true, true),
  ('858', 'Autres dotations HAO', 8, 'charge', true, true),
  ('86', 'Reprises de charges, provisions et dépréciations HAO', 8, 'produit', true, true),
  ('861', 'Reprises de provisions réglementées', 8, 'produit', true, true),
  ('862', 'Reprises d''amortissements HAO', 8, 'produit', true, true),
  ('863', 'Reprises de dépréciations HAO', 8, 'produit', true, true),
  ('864', 'Reprises de provisions pour risques et charges HAO', 8, 'produit', true, true),
  ('865', 'Reprises de subventions d''investissement', 8, 'produit', true, true),
  ('868', 'Autres reprises HAO', 8, 'produit', true, true),
  ('87', 'Participation des travailleurs', 8, 'charge', true, true),
  ('871', 'Participation légale aux bénéfices', 8, 'charge', true, true),
  ('874', 'Participation contractuelle aux bénéfices', 8, 'charge', true, true),
  ('878', 'Autres participations', 8, 'charge', true, true),
  ('88', 'Subventions d''équilibre', 8, 'produit', true, true),
  ('881', 'Subventions d''équilibre de l''État', 8, 'produit', true, true),
  ('884', 'Subventions d''équilibre des collectivités publiques', 8, 'produit', true, true),
  ('886', 'Subventions d''équilibre du groupe', 8, 'produit', true, true),
  ('888', 'Autres subventions d''équilibre', 8, 'produit', true, true),
  ('89', 'Impôts sur le résultat', 8, 'charge', true, true),
  ('891', 'Impôts sur les bénéfices de l''exercice', 8, 'charge', true, true),
  ('892', 'Rappels d''impôts sur résultats antérieurs', 8, 'charge', true, true),
  ('895', 'Impôt minimum forfaitaire (IMF)', 8, 'charge', true, true),
  ('899', 'Dégrèvements et annulations d''impôts sur résultats antérieurs', 8, 'charge', true, true)
on conflict (code) do update set standard = true, classe = excluded.classe;

-- 2. Reprise des comptes du plan d'origine
create temp table if not exists _reprise_pc (ancien text primary key, nouveau text not null, garder_libelle boolean not null);
truncate _reprise_pc;
insert into _reprise_pc values
  ('101000', '101', false),
  ('106000', '118', false),
  ('110000', '121', false),
  ('120000', '131', false),
  ('129000', '139', false),
  ('162000', '162', false),
  ('168000', '168', false),
  ('213000', '213', false),
  ('222000', '223', false),
  ('231000', '231', false),
  ('241000', '241', false),
  ('244000', '244', false),
  ('245000', '245', false),
  ('281300', '2813', false),
  ('283100', '2831', false),
  ('284100', '2841', false),
  ('284500', '2845', false),
  ('321000', '321', true),
  ('322000', '322', true),
  ('323000', '323', true),
  ('331000', '331', false),
  ('401000', '4011', false),
  ('408000', '408', false),
  ('409000', '4091', false),
  ('411000', '4111', false),
  ('416000', '416', false),
  ('418000', '418', false),
  ('419000', '4191', false),
  ('421000', '422', false),
  ('422000', '421', false),
  ('431000', '431', false),
  ('441000', '441', false),
  ('443000', '4431', false),
  ('444100', '4441', false),
  ('444900', '4449', false),
  ('445000', '4452', false),
  ('447000', '442', false),
  ('512000', '521', false),
  ('571000', '571', true),
  ('572000', '572', true),
  ('585000', '585', false),
  ('601000', '602', false),
  ('602000', '602', false),
  ('605000', '608', false),
  ('614000', '611', false),
  ('621000', '621', false),
  ('622000', '622', false),
  ('624000', '624', false),
  ('625000', '625', false),
  ('627000', '627', false),
  ('628000', '638', false),
  ('631000', '631', false),
  ('633000', '633', false),
  ('638000', '638', false),
  ('641000', '641', false),
  ('658000', '658', false),
  ('661000', '661', false),
  ('664000', '664', false),
  ('668000', '668', false),
  ('671000', '671', false),
  ('678000', '674', false),
  ('681000', '681', false),
  ('701000', '701', false),
  ('706000', '706', false),
  ('758000', '758', false),
  ('771000', '771', false),
  ('891000', '891', false);
delete from _reprise_pc r where not exists (select 1 from public.compta_comptes c where c.code = r.ancien);
update public.compta_comptes n set libelle = o.libelle
  from _reprise_pc r join public.compta_comptes o on o.code = r.ancien where n.code = r.nouveau and r.garder_libelle;
update public.compta_lignes x set compte_code = r.nouveau from _reprise_pc r where x.compte_code = r.ancien;
update public.caisses x set compte_code = r.nouveau from _reprise_pc r where x.compte_code = r.ancien;
update public.caisse_mouvements x set compte_ventile = r.nouveau from _reprise_pc r where x.compte_ventile = r.ancien;
update public.caisse_regles_ventilation x set compte_code = r.nouveau from _reprise_pc r where x.compte_code = r.ancien;
update public.parametres p set comptes_defaut = (
    select coalesce(jsonb_object_agg(e.key, coalesce((select r.nouveau from _reprise_pc r where r.ancien = e.value), e.value)), '{}'::jsonb)
    from jsonb_each_text(p.comptes_defaut) e)
  where p.comptes_defaut is not null and p.comptes_defaut <> '{}'::jsonb;
delete from public.compta_comptes c using _reprise_pc r where c.code = r.ancien;
drop table _reprise_pc;

-- 3. Compte de regroupement = non imputable (il a des sous-comptes actifs)
create or replace function public.compta_compte_est_regroupement(p_code text) returns boolean
language sql stable set search_path = public as $$
  select exists (select 1 from compta_comptes c where c.actif and c.code <> p_code and left(c.code, length(p_code)) = p_code);
$$;
create or replace function public.compta_lignes_garde_imputable() returns trigger
language plpgsql set search_path = public as $$
begin
  if public.compta_compte_est_regroupement(new.compte_code) then
    raise exception 'Le compte % est un compte de regroupement (il a des sous-comptes) : imputez l''écriture sur l''un de ses sous-comptes.', new.compte_code
      using errcode = 'check_violation';
  end if;
  return new;
end $$;
drop trigger if exists trg_compta_lignes_imputable on public.compta_lignes;
create trigger trg_compta_lignes_imputable before insert or update of compte_code on public.compta_lignes
  for each row execute function public.compta_lignes_garde_imputable();

-- 4. Journaux
insert into public.compta_journaux (code, libelle) values
  ('AC','Journal des Achats'),('AN','Journal des À-Nouveaux'),('BQ','Journal de Banque'),('CA','Journal de Caisse'),
  ('CLO','Journal de Clôture'),('MM','Journal Mobile Money'),('OD','Journal des Opérations Diverses'),('VE','Journal des Ventes'),
  ('INV','Journal d''inventaire (variations de stocks)')
on conflict (code) do nothing;

-- 5. Comptabilisation automatique des bons validés par le DG : le compte d'imputation choisi sur le bon
--    (caisse_demandes.compte_imputation) est reporté sur le mouvement (compte proposé, statut « à ventiler »),
--    les transferts sur le compte de virements de fonds ; l'application génère ensuite l'écriture.
create or replace function public.caisse_demande_decider(p_id uuid, p_decision text, p_motif text default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare d caisse_demandes; s_src uuid; s_dst uuid; v_num text; n int; v_trf uuid; m1 uuid; m2 uuid;
        v_nom text; c_src text; c_dst text; v_cpt_vir text;
begin
  if auth.uid() is null then raise exception 'Non authentifié'; end if;
  select * into d from caisse_demandes where id = p_id for update;
  if d.id is null then return jsonb_build_object('ok',false,'message','Demande introuvable'); end if;
  if d.statut <> 'en_attente' then return jsonb_build_object('ok',false,'message','Cette demande a déjà été traitée ('||d.statut||')'); end if;
  if not public.peut_valider_caisse(d.montant) then
    return jsonb_build_object('ok',false,'message','🔒 Votre plafond de validation ne couvre pas '||replace(to_char(d.montant,'FM999,999,999,990'),',',' ')||' FCFA : un responsable habilité (DG) doit intervenir.');
  end if;
  select coalesce(nom_complet, login) into v_nom from profiles where id = auth.uid();
  if p_decision = 'rejeter' then
    if coalesce(trim(p_motif),'') = '' then return jsonb_build_object('ok',false,'message','Motif du rejet obligatoire'); end if;
    update caisse_demandes set statut='rejetee', motif_rejet=trim(p_motif), decide_par=auth.uid(), decide_nom=v_nom, decide_le=now() where id = d.id;
    return jsonb_build_object('ok',true,'statut','rejetee');
  end if;
  if p_decision <> 'valider' then raise exception 'Décision inconnue'; end if;

  -- Séance ouverte de la caisse (celle de la demande si elle l'est encore)
  select id into s_src from caisse_sessions where caisse_id = d.caisse_id and statut = 'ouverte'
    order by (id = d.session_id) desc, ouverte_le desc limit 1;
  select nom into c_src from caisses where id = d.caisse_id;
  if s_src is null then
    return jsonb_build_object('ok',false,'message','Aucune séance ouverte sur la caisse « '||coalesce(c_src,'')||' » : ouvrez-la pour valider (le bon s''inscrit dans le solde de la séance).');
  end if;
  perform set_config('app.caisse_validation', '1', true);
  if d.type = 'transfert' then
    select id into s_dst from caisse_sessions where caisse_id = d.caisse_dest_id and statut = 'ouverte' order by ouverte_le desc limit 1;
    select nom into c_dst from caisses where id = d.caisse_dest_id;
    if s_dst is null then return jsonb_build_object('ok',false,'message','La caisse destination « '||coalesce(c_dst,'')||' » doit avoir une séance ouverte.'); end if;
    v_trf := gen_random_uuid();
    -- Comptabilisation automatique : un transfert se ventile sur le compte de virements de fonds (585)
    select coalesce(nullif(comptes_defaut->>'virement_interne',''), '585') into v_cpt_vir from parametres limit 1;
    v_cpt_vir := coalesce(v_cpt_vir, '585');
    if not exists (select 1 from compta_comptes where code = v_cpt_vir) then v_cpt_vir := null; end if;
    insert into caisse_mouvements (session_id, caisse_id, numero, date_mouvement, type, montant, motif, beneficiaire, statut, transfert_id, created_by, projet_id, compte_ventile)
      values (s_src, d.caisse_id, 'TRF-OUT', current_date, 'sortie', d.montant, coalesce(nullif(d.motif,''), 'Transfert vers '||coalesce(c_dst,'caisse')), d.beneficiaire, 'a_ventiler', v_trf, d.demande_par, d.projet_id, v_cpt_vir)
      returning id into m1;
    insert into caisse_mouvements (session_id, caisse_id, numero, date_mouvement, type, montant, motif, statut, transfert_id, created_by, compte_ventile)
      values (s_dst, d.caisse_dest_id, 'TRF-IN', current_date, 'entree', d.montant, 'Transfert depuis '||coalesce(c_src,'caisse'), 'a_ventiler', v_trf, d.demande_par, v_cpt_vir)
      returning id into m2;
  else
    perform pg_advisory_xact_lock(hashtext('caisse_bons_' || d.caisse_id::text));
    select greatest(count(*), coalesce(max(nullif(regexp_replace(numero, '^.*-', ''), '')::int) filter (where numero ~ '^(BE|BS)-[0-9]+$'), 0)) + 1
      into n from caisse_mouvements where caisse_id = d.caisse_id;
    v_num := (case when d.type = 'entree' then 'BE' else 'BS' end) || '-' || lpad(n::text, 5, '0');
    insert into caisse_mouvements (session_id, caisse_id, numero, date_mouvement, type, montant, motif, beneficiaire, statut, created_by, projet_id, compte_ventile)
      values (s_src, d.caisse_id, v_num, d.date_mouvement, d.type, d.montant, d.motif, d.beneficiaire, 'a_ventiler', d.demande_par, d.projet_id, d.compte_imputation)
      returning id into m1;
  end if;
  update caisse_demandes set statut='validee', decide_par=auth.uid(), decide_nom=v_nom, decide_le=now(), mouvement_id=m1, mouvement_dest_id=m2 where id = d.id;
  return jsonb_build_object('ok',true,'statut','validee','mouvement_id',m1,'numero',coalesce(v_num,'TRF'));
end $$;
